# Generated by Django 2.2.8 on 2020-02-09 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='anonymous_user',
            field=models.CharField(default='', max_length=256, verbose_name='ID сессии'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
