# Generated by Django 2.2.8 on 2020-02-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site_app', '0003_auto_20200209_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(blank=True, default='Анонимный отзыв', max_length=50, null=True, verbose_name='Автор'),
        ),
    ]
